In [1]:
import numpy as np
import pandas as pd
import polars as pl
import os
import csv
from datetime import datetime, timedelta
import rdata
import pyreadr as pr

In [2]:
path_Herzraten = "../Wildschwein_Eisenstadt/Herzraten"
path_Klimadaten = "../Wildschwein_Eisenstadt/Klimadaten"
path_StarOddi_Backup = "../Wildschwein_Eisenstadt/StarOddi Backup"
path_Suhlenlogger = "../Wildschwein_Eisenstadt/Suhlenlogger"
path_Telemetriedate = "../Wildschwein_Eisenstadt/Telemetriedaten"
path_Temperaturlogger = "../Wildschwein_Eisenstadt/Temperaturlogger"
path_Wichtige_Projektfiles = "../Wildschwein_Eisenstadt/Wichtige Projektfiles"

## Herzraten

In [46]:
Herzraten_csv = os.path.join(path_Herzraten,"csv files")
Herzraten_Fiwi = os.path.join(path_Herzraten,"Fiwi")
Herzraten_Schützen = os.path.join(path_Herzraten,"Schützen")
Herzraten_Tests = os.path.join(path_Herzraten,"TestsAndEvaluations")

What mean the acronym

On one hand (In the principle of the name):
- HR: heart rate

On the other (Inside of the name):

- DE
- IS

### CSV_files

In [47]:
csv_file_path = os.listdir(Herzraten_csv)

What is each of the part ?

- hr - hear rate
- 2016 - year of the data 
- DE.2011.14 - ID
- DE - Gatter/Fuetterung (Area name)

from 2016/10/14 to 2019/06/25

QI is a kind of categorie (I am not sure about what is)

In [48]:
# hr_2016_DE.2011.14.csv
df = pl.read_csv(os.path.join(Herzraten_csv,csv_file_path[0]))
df

shape: (44025, 4)
┌──────────────────┬─────────┬───────────┬─────┐
│ Date             ┆ Temp    ┆ HeartRate ┆ QI  │
│ ---              ┆ ---     ┆ ---       ┆ --- │
│ str              ┆ f64     ┆ i64       ┆ i64 │
╞══════════════════╪═════════╪═══════════╪═════╡
│ 2016/10/14 12:00 ┆ 23.6    ┆ 227       ┆ 3   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 2016/10/14 12:12 ┆ 18.45   ┆ 51        ┆ 2   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 2016/10/14 12:24 ┆ 16.8    ┆ 194       ┆ 2   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 2016/10/14 12:36 ┆ 16.47   ┆ 335       ┆ 3   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ ...              ┆ ...     ┆ ...       ┆ ... │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 2017/10/16 08:12 ┆ -218.27 ┆ 1023      ┆ 3   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 2017/10/16 08:24 ┆ -218.27 ┆ 1023      ┆ 3   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 2017/10/16 08:36 ┆ -218.27 ┆ 1023      ┆ 3   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 2017/10/16 08:48 ┆ -218.27 ┆ 1023      ┆ 3   │
└──────────────────┴─────────┴───────────┴─────┘

In [6]:
df[2,0]

'2016/10/14 12:24'

### FIWI

Inside of the name folders we have a code "CHL0062" with information inside with extension CCD, CCT ... I think that is genetic information

In [7]:
fiwi_path = os.listdir(Herzraten_Fiwi)[1:]

In [21]:
# We will analyze heidi data.
heidi_herzraten_data = os.path.join(Herzraten_Fiwi,fiwi_path[0])
files_heidi = os.listdir(heidi_herzraten_data)

In [47]:
df = pd.read_excel(os.path.join(heidi_herzraten_data,files_heidi[1]))
df = pl.DataFrame(df)
df = df.filter(pl.col("Temp(°C)") > -168.45)
df

shape: (31920, 4)
┌─────────────────────┬──────────┬─────────────────┬─────┐
│ Date & Time         ┆ Temp(°C) ┆ Heart rate(bpm) ┆ QI  │
│ ---                 ┆ ---      ┆ ---             ┆ --- │
│ datetime[ns]        ┆ f64      ┆ i64             ┆ i64 │
╞═════════════════════╪══════════╪═════════════════╪═════╡
│ 2017-08-28 09:00:00 ┆ 23.83    ┆ 114             ┆ 2   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 2017-08-28 09:12:00 ┆ 23.83    ┆ 1               ┆ 3   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 2017-08-28 09:24:00 ┆ 23.93    ┆ 0               ┆ 3   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 2017-08-28 09:36:00 ┆ 24.15    ┆ 0               ┆ 3   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ ...                 ┆ ...      ┆ ...             ┆ ... │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 2018-05-21 08:12:00 ┆ 37.0     ┆ 70              ┆ 0   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 2018-05-21 08:24:00 ┆ 36.94    ┆ 86              ┆ 0   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 2018-05-21 08:36:00 ┆ 36.64    ┆ 70              ┆ 0   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 2018-05-21 08:48:00 ┆ 35.17    ┆ 50              ┆ 0   │
└─────────────────────┴──────────┴─────────────────┴─────┘

### Schützen

Each of the files to a wild boar?, ge14 also they have de Id

- ge14
- DE.2011.25

In [71]:
schutzen_path = os.listdir(Herzraten_Schützen)
schutzen_path

['ge14_2016',
 'ge14_2017',
 'ge21_2016',
 'or01_2017',
 'or04_2017',
 'or11_2017',
 'or12_2017',
 'rs08_2017',
 'rt07_2016',
 'vl06_2017',
 'vl08_2016']

In [66]:
ge14_2016_herzraten_data = os.path.join(Herzraten_Schützen,schutzen_path[0])
ge14_2016_herzraten = os.listdir(ge14_2016_herzraten_data)
ge14_2016_herzraten

['CHL0021', 'hr_2016_DE.2011.14.xlsx', '~$hr_2016_DE.2011.14.xlsx']

In [69]:
df = pd.read_excel(os.path.join(ge14_2016_herzraten_data,"hr_2016_DE.2011.14.xlsx"))
df = pl.DataFrame(df)
df

shape: (44025, 4)
┌─────────────────────┬──────────┬─────────────────┬─────┐
│ Date & Time         ┆ Temp(°C) ┆ Heart rate(bpm) ┆ QI  │
│ ---                 ┆ ---      ┆ ---             ┆ --- │
│ datetime[ns]        ┆ f64      ┆ i64             ┆ i64 │
╞═════════════════════╪══════════╪═════════════════╪═════╡
│ 2016-10-14 12:00:00 ┆ 23.6     ┆ 227             ┆ 3   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 2016-10-14 12:12:00 ┆ 18.45    ┆ 51              ┆ 2   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 2016-10-14 12:24:00 ┆ 16.8     ┆ 194             ┆ 2   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 2016-10-14 12:36:00 ┆ 16.47    ┆ 335             ┆ 3   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ ...                 ┆ ...      ┆ ...             ┆ ... │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 2017-10-16 08:12:00 ┆ -218.27  ┆ 1023            ┆ 3   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 2017-10-16 08:24:00 ┆ -218.27  ┆ 1023            ┆ 3   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 2017-10-16 08:36:00 ┆ -218.27  ┆ 1023            ┆ 3   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┤
│ 2017-10-16 08:48:00 ┆ -218.27  ┆ 1023            ┆ 3   │
└─────────────────────┴──────────┴─────────────────┴─────┘

### Test And Evaluations

In [6]:
testEva_path = os.listdir(Herzraten_Tests)
testEva_path

['EavlRQI_rt07_CHL0025.xlsx',
 'Test_ge21_CHL0024.xlsx',
 'Test_vl08_CHL0025.xlsx']

In [21]:
df = pd.read_excel(os.path.join(Herzraten_Tests,"EavlRQI_rt07_CHL0025.xlsx"),sheet_name=['RQI_2CHL0025','RQI_modified',"QI limits"])
df_2chl0025 = df.get("RQI_2CHL0025")
df_2chl0025_1 = df_2chl0025.iloc[:5,:7]
df_2chl0025_2 = df_2chl0025.iloc[5:,1:8]

In [22]:
df_modified = df.get("RQI_modified")
df_modified_1 = df_modified.iloc[:5,:7]
df_modified_2 = df_modified.iloc[5:,1:8]

In [24]:
df_limits = df.get("QI limits")
df_limits

Mercury limits       Unnamed: 1      Unnamed: 2         Unnamed: 3  \
0             Fs  Theoretical Min  Guaranteed Min  Mercury (min BPM)   
1            200               20              40                 40   
2            200               20              40                 20   

          Unnamed: 4                Unnamed: 5  \
0  Mercury (max BPM)  Mercury (One per Buffer)   
1                200                        20   
2                300                         1   

                         Unnamed: 6  
0                               NaN  
1  <- OLD Limits (before 28.4.2017)  
2   <- NEW Limits (after 28.4.2017)

In [28]:
df = pd.read_excel(os.path.join(Herzraten_Tests,"Test_ge21_CHL0024.xlsx"),sheet_name=['DAT','XY'])
df_test_ge21_dat = df.get("DAT")
df_test_ge21_XY = df.get("XY")

In [29]:
df = pd.read_excel(os.path.join(Herzraten_Tests,"Test_vl08_CHL0025.xlsx"),sheet_name=['DAT','XY'])
df_test_vl08_dat = df.get("DAT")
df_test_vl08_XY = df.get("XY")

## Klimadaten

In [70]:
Klimadaten_Logger = os.path.join(path_Klimadaten,"Logger")
Klimadaten_Wetterstation = os.path.join(path_Klimadaten,"Wetterstation")
Klimadaten_Eisenstadt_ZAMG = os.path.join(path_Klimadaten,"Eisenstadt ZAMG.xlsx")

Temperature of Eisenstadt ZAMG ? 

### Eisenstadt ZAMG

In [71]:
df = pd.read_excel(Klimadaten_Eisenstadt_ZAMG)
df

Year  Month  Mean temperature  Maximum Temperature  Minimum Temperature  \
0   2011    1.0               0.4                 13.7                -10.9   
1   2011    2.0               0.1                 15.2                 -9.3   
2   2011    3.0               6.2                 21.4                 -6.5   
3   2011    4.0              13.4                 27.4                  5.2   
4   2011    5.0              16.0                 28.5                  2.2   
5   2011    6.0              19.7                 30.6                 10.9   
6   2011    7.0              19.7                 34.6                 11.2   
7   2011    8.0              21.0                 35.5                  9.2   
8   2011    9.0              18.1                 31.4                  9.3   
9   2011   10.0              10.1                 26.5                  0.3   
10  2011   11.0               3.0                 15.5                 -3.7   
11  2011   12.0               3.2                 12.6                 -4.3   
12  2012    1.0               2.4                 11.4                 -9.0   
13  2012    2.0              -1.8                 14.7                -14.8   
14  2012    3.0               8.8                 21.9                 -5.3   
15  2012    4.0              11.1                 30.0                 -0.7   
16  2012    5.0              16.9                 30.5                  2.4   
17  2012    6.0              20.7                 35.9                  6.8   
18  2012    7.0              21.6                 36.3                 11.8   
19  2012    8.0              21.3                 35.3                 10.6   
20  2012    9.0              16.7                 31.4                  5.4   
21  2012   10.0              10.1                 24.9                 -2.6   
22  2012   11.0               6.8                 16.8                  0.8   
23  2012   12.0               0.2                  8.6                 -8.9   
24  2013    1.0               0.2                 14.7                -12.2   
25  2013    2.0               1.0                 12.2                 -6.8   
26  2013    3.0               3.0                 19.8                 -6.2   
27  2013    4.0              11.8                 27.7                 -1.4   
28  2013    5.0              15.1                 26.3                  7.3   
29  2013    6.0              18.8                 33.9                  7.3   
30  2013    7.0              23.1                 37.0                  9.7   
31  2013    8.0              21.6                 39.3                 11.8   
32  2013    9.0              15.0                 27.1                  5.4   
33  2013   10.0              11.0                 22.7                  0.6   
34  2013   11.0               6.0                 19.3                 -5.4   
35  2013   12.0               2.8                 13.7                 -3.7   
36  2014    NaN               NaN                  NaN                  NaN   

    Precipitation amount  
0                   22.0  
1                    3.0  
2                   41.0  
3                   21.0  
4                   83.0  
5                  155.0  
6                   45.0  
7                   85.0  
8                   61.0  
9                   85.0  
10                   0.0  
11                  11.0  
12                  53.0  
13                  16.0  
14                   6.0  
15                  37.4  
16                  40.0  
17                  62.0  
18                 200.0  
19                  61.0  
20                  51.5  
21                  51.0  
22                  49.0  
23                  35.0  
24                  69.0  
25                  72.0  
26                  51.0  
27                  16.0  
28                  71.0  
29                 100.0  
30                   4.0  
31                  56.0  
32                  85.0  
33                  26.0  
34                  92.6  
35                   9.0  
36

### Logger

In [77]:
Klimadaten_Logger = os.path.join(path_Klimadaten,"Logger")
files = os.listdir(Klimadaten_Logger)
files_FG = [w for w in files if "FG" in w and not "alldata" in w]

In [79]:
result = pd.DataFrame()
for file in files_FG:
    df = pd.read_csv(os.path.join(Klimadaten_Logger,file), sep=",",encoding= 'unicode_escape')
    df.columns = ["Logger 1 FG","Time","Celsius(°C)","Humidity(%rh)","dew point(°C)"]
    result = pd.concat([result,df.iloc[:,1:]])
result = result.reset_index(drop=True)
result

Time  Celsius(°C)  Humidity(%rh) dew point(°C)
0      24/09/2011 00:00:00         15.5           76.5          11.4
1      24/09/2011 01:00:00         15.5           77.0          11.5
2      24/09/2011 02:00:00         15.0           80.0          11.6
3      24/09/2011 03:00:00         14.0           83.0          11.2
4      24/09/2011 04:00:00         14.0           80.5          10.7
...                    ...          ...            ...           ...
52787  13/10/2017 06:00:00         14.5           78.5          10.8
52788  13/10/2017 07:00:00         14.0           83.0          11.2
52789  13/10/2017 08:00:00         12.5           86.5          10.3
52790  13/10/2017 09:00:00         15.0           79.5          11.5
52791  13/10/2017 10:00:00         15.5           78.0          11.7

[52792 rows x 4 columns]

In [80]:
result.to_csv(os.path.join(Klimadaten_Logger,"Logger 1 FG.csv"),index=False)
result.to_excel(os.path.join(Klimadaten_Logger,"Logger 1 FG.xlsx"),index=False)

In [81]:
files_VG = [w for w in files if "VG" in w]

In [86]:
result = pd.DataFrame()
for file in files_VG:
    df = pd.read_csv(os.path.join(Klimadaten_Logger,file), sep=",",encoding= 'unicode_escape')
    df.columns = ["Logger 1 VG","Time","Celsius(°C)","Humidity(%rh)","dew point(°C)","Serial Number"]
    result = pd.concat([result,df.iloc[:,1:]])


In [87]:
result["Time"] = pd.to_datetime(result["Time"],format="%d/%m/%Y %H:%M:%S")
result.sort_values(by='Time', inplace=True)
result = result.reset_index(drop=True)

In [88]:
result.to_csv(os.path.join(Klimadaten_Logger,"Logger 1 VG.csv"),index=False)
result.to_excel(os.path.join(Klimadaten_Logger,"Logger 1 VG.xlsx"),index=False)

### Wetterstation

For some reason the file Klima_2019.06.24-2019.08.21.csv have different columns name, so i have to change all of the columns name in all the files

In [46]:
wetter_files = os.listdir(Klimadaten_Wetterstation)
wetter_files

wetter_files_csv = [w for w in wetter_files if "Klima_" in w]

In [47]:
wetter_files_csv

['Klima_2016.12.11-2017.12.31.csv',
 'Klima_2018.01.01-2018.09.24.csv',
 'Klima_2018.10.25-2018.12.31.csv',
 'Klima_2019.01.01-2019.06.24.csv',
 'Klima_2019.06.24-2019.08.21.csv']

In [88]:
result = pd.DataFrame()
columns = ['Day of the Week ', 'Date Time ', 'Outside Temperature TX4 (°C)',
       'Outside Humidity TX4 (%)', 'Wind Speed TX4 (k/hr)',
       'Dominant Wind Dir TX4', 'Rain Amount TX4 (mm)', 'Solar Radiation TX4',
       'Radio RSSI TX4', 'Outside Temperature TX5 (°C)', 'Radio RSSI TX5',
       'Outside Temperature TX6 (°C)', 'Outside Humidity TX6 (%)',
       'Radio RSSI TX6', 'Inside Temperature (°C)', 'Inside Humidity (%)',
       'Barometric Pressure (mb)', 'Receiver Battery Voltage (volts)']
for file in wetter_files_csv:
    df = pd.read_csv(os.path.join(Klimadaten_Wetterstation,file),encoding= 'unicode_escape')
    df.columns = columns
    result = pd.concat([result,df.iloc[:,:]])
    if file == "Klima_2019.06.24-2019.08.21.csv":
        result["Date Time "] = pd.to_datetime(result["Date Time "],format="%Y-%m-%d %H:%M:%S")
    else:
        result["Date Time "] = pd.to_datetime(result["Date Time "],format="%Y/%m/%d %H:%M:%S")
result = result.reset_index(drop=True)
result.sort_values(by='Date Time ', inplace=True)
result


Day of the Week           Date Time   Outside Temperature TX4 (°C)  \
0                   Sun 2016-12-11 00:50:00                          20.5   
1                   Sun 2016-12-11 01:00:00                          20.5   
2                   Sun 2016-12-11 01:10:00                          20.5   
3                   Sun 2016-12-11 01:20:00                          20.5   
4                   Sun 2016-12-11 01:30:00                          20.5   
...                 ...                 ...                           ...   
137145              Wed 2019-08-21 13:00:00                          20.5   
137146              Wed 2019-08-21 13:10:00                          20.3   
137147              Wed 2019-08-21 13:20:00                          20.4   
137148              Wed 2019-08-21 13:30:00                          20.3   
137149              Wed 2019-08-21 13:40:00                          19.9   

        Outside Humidity TX4 (%)  Wind Speed TX4 (k/hr) Dominant Wind Dir TX4  \
0                             35                    0.0                   NaN   
1                             35                    0.0                   NaN   
2                             35                    0.0                   NaN   
3                             35                    0.0                   NaN   
4                             35                    0.0                   NaN   
...                          ...                    ...                   ...   
137145                        65                    8.1                    NW   
137146                        66                   10.3                    NW   
137147                        67                    8.2                    NW   
137148                        67                   10.1                   NNW   
137149                        69                   10.8                    NW   

        Rain Amount TX4 (mm)  Solar Radiation TX4  Radio RSSI TX4  \
0                        0.0                    0              58   
1                        0.0                    0              58   
2                        0.0                    0              58   
3                        0.0                    0              58   
4                        0.0                    0              58   
...                      ...                  ...             ...   
137145                   0.0                  386              37   
137146                   0.0                  370              38   
137147                   0.0                  399              38   
137148                   0.0                  431              38   
137149                   0.0                  385              39   

        Outside Temperature TX5 (°C)  Radio RSSI TX5  \
0                               20.6            58.0   
1                               20.6            58.0   
2                               20.6            58.0   
3                               20.6            58.0   
4                               20.6            58.0   
...                              ...             ...   
137145                          28.0            41.0   
137146                          27.3            41.0   
137147                          27.2            40.0   
137148                          27.2            41.0   
137149                          26.8            41.0   

        Outside Temperature TX6 (°C)  Outside Humidity TX6 (%)  \
0                               20.3                        36   
1                               20.3                        36   
2                               20.3                        36   
3                               20.3                        36   
4                               20.3                        36   
...                              ...                       ...   
137145                          20.3                        66   
137146                          20.3                        66   
137147       

In [89]:
result.to_csv(os.path.join(Klimadaten_Wetterstation,"clima.csv"),index=False)
result.to_excel(os.path.join(Klimadaten_Wetterstation,"clima.xlsx"),index=False)

join wettersation

In [142]:
df_diagnosticData = pd.read_csv(os.path.join(Klimadaten_Wetterstation,"Wetterstation_2016.12.05-2019.06.24","DiagnosticData.txt"), header = 1,sep=",",encoding= 'unicode_escape')
df_diagnosticData["RecDateTime"] = pd.to_datetime(df_diagnosticData["RecDateTime"],format="%Y-%m-%d %H:%M:%S")
df_diagnosticData

ReceiverRecID  ChannelIndex         RecDateTime  PacketsReceived  \
0                   2             5 2016-12-05 18:00:00              166   
1                   2             3 2016-12-05 18:10:00              164   
2                   2             4 2016-12-05 18:10:00              167   
3                   2             5 2016-12-05 18:10:00              158   
4                   2             3 2016-12-05 18:20:00              170   
...               ...           ...                 ...              ...   
388534              2             4 2019-06-24 10:40:00                0   
388535              2             5 2019-06-24 10:40:00              200   
388536              2             3 2019-06-24 10:50:00              218   
388537              2             4 2019-06-24 10:50:00                0   
388538              2             5 2019-06-24 10:50:00              198   

        SuperCapVol  SolarPanelVol  ChannelBatteryVol  ReedClosed  ReedOpen  \
0                -1             -1                 -1           0         0   
1                -1             -1                 -1           0       153   
2                -1             -1                 -1           0         0   
3                -1             -1                 -1           0         0   
4                -1             -1                 -1           0       159   
...             ...            ...                ...         ...       ...   
388534           -1             -1                 -1           0         0   
388535           -1             -1                 -1           0         0   
388536           -1             -1                 -1           2       205   
388537           -1             -1                 -1           0         0   
388538           -1             -1                 -1           0         0   

        RadioRSSI  RadioAFC  RadioResynchs  TXStatus  IntervalIndex  
0              58         0              0         0              0  
1              58         0              0         0              0  
2              58         3              0         0              0  
3              58         0              0         0              0  
4              58         0              0         0              0  
...           ...       ...            ...       ...            ...  
388534        255      -128              0         2              0  
388535         37         1              0         0              0  
388536         38         2              0         0              0  
388537        255      -128              1         2              0  
388538         37         1              0         0              0  

[388539 rows x 14 columns]

In [143]:
df_Inside = pd.read_csv(os.path.join(Klimadaten_Wetterstation,"Wetterstation_2016.12.05-2019.06.24","InsideData.txt"), header = 1,sep=",",encoding= 'unicode_escape')
df_Inside["RecDateTime"] = pd.to_datetime(df_Inside["RecDateTime"],format="%Y-%m-%d %H:%M:%S")
df_Inside

ReceiverRecID  ChannelIndex         RecDateTime  Barometer  TempIn  \
0                   2             8 2016-12-05 11:50:00      30359     729   
1                   2             8 2016-12-05 12:10:00      30356     725   
2                   2             8 2016-12-05 12:20:00      30353     722   
3                   2             8 2016-12-05 12:30:00      30350     719   
4                   2             8 2016-12-05 12:40:00      30352     717   
...               ...           ...                 ...        ...     ...   
129508              2             8 2019-06-24 10:10:00      30807     723   
129509              2             8 2019-06-24 10:20:00      30811     730   
129510              2             8 2019-06-24 10:30:00      30811     739   
129511              2             8 2019-06-24 10:40:00      30813     744   
129512              2             8 2019-06-24 10:50:00      30812     757   

        HumIn  DewPointIn  HeatIndexIn  ConsoleBatteryVol  GlobalStatus  \
0          36         443          710                704             1   
1          37         446          710                704             1   
2          36         437          700                704             1   
3          37         441          700                705             1   
4          37         439          690                705             1   
...       ...         ...          ...                ...           ...   
129508     72         628          740                806             1   
129509     72         634          750                807             1   
129510     72         643          760                805             1   
129511     72         648          760                806             1   
129512     72         660          780                806             1   

        IntervalIndex  
0                   0  
1                   0  
2                   0  
3                   0  
4                   0  
...               ...  
129508              0  
129509              0  
129510              0  
129511              0  
129512              0  

[129513 rows x 11 columns]

In [144]:
df_ISSData = pd.read_csv(os.path.join(Klimadaten_Wetterstation,"Wetterstation_2016.12.05-2019.06.24","ISSData.txt"), header = 1,sep=",",encoding= 'unicode_escape')
df_ISSData["RecDateTime"] = pd.to_datetime(df_ISSData["RecDateTime"],format="%Y-%m-%d %H:%M:%S")
df_ISSData

ReceiverRecID  ChannelIndex         RecDateTime  TempOut  HiTempOut  \
0                   2             3 2016-12-05 22:50:00      679        680   
1                   2             3 2016-12-05 23:00:00      679        680   
2                   2             3 2016-12-05 23:10:00      679        680   
3                   2             3 2016-12-05 23:20:00      680        680   
4                   2             3 2016-12-05 23:30:00      679        680   
...               ...           ...                 ...      ...        ...   
129508              2             3 2019-06-24 10:10:00      730        730   
129509              2             3 2019-06-24 10:20:00      735        735   
129510              2             3 2019-06-24 10:30:00      738        741   
129511              2             3 2019-06-24 10:40:00      742        742   
129512              2             3 2019-06-24 10:50:00      750        750   

        LowTempOut  HumOut  WindSpeed  ScalerAvgWindDir  HiWindSpeed  ...  \
0              679      36          0                 0            0  ...   
1              679      36          0                 0            0  ...   
2              679      36          0                 0            0  ...   
3              679      35          0                 0            0  ...   
4              678      35          0                 0            0  ...   
...            ...     ...        ...               ...          ...  ...   
129508         723      68        121                 0          272  ...   
129509         730      67        118                 0          272  ...   
129510         735      65        114                 0          320  ...   
129511         736      65        106                 0          288  ...   
129512         742      67         98                 0          208  ...   

        RainCollectorType  RainCollectorInc  TotalRainClicks  HiRainRate  ET  \
0                       1          0.007874                0           0   0   
1                       1          0.007874                0           0   2   
2                       1          0.007874                0           0   0   
3                       1          0.007874                0           0   0   
4                       1          0.007874                0           0   0   
...                   ...               ...              ...         ...  ..   
129508                  1          0.007874                0           0   0   
129509                  1          0.007874                0           0   0   
129510                  1          0.007874                0           0   0   
129511                  1          0.007874                0           0   0   
129512                  1          0.007874                0           0   0   

         UV  HiUV  SolarRad  HiSolarRad  IntervalIndex  
0       255     0         0           0              0  
1       255     0         0           0              0  
2       255     0         0           0              0  
3       255     0         0           0              0  
4       255     0         0           0              0  
...     ...   ...       ...         ...            ...  
129508  255     0       693         721              0  
129509  255     0       746         793              0  
129510  255     0       741         768              0  
129511  255     0       669         773              0  
129512  255     0       841         879              0  

[129513 rows x 26 columns]

In [146]:
df_TempHumData = pd.read_csv(os.path.join(Klimadaten_Wetterstation,"Wetterstation_2016.12.05-2019.06.24","TempHumData.txt"), header = 1,sep=",",encoding= 'unicode_escape')
df_TempHumData["RecDateTime"] = pd.to_datetime(df_TempHumData["RecDateTime"],format="%Y-%m-%d %H:%M:%S")
df_TempHumData

ReceiverRecID  ChannelIndex         RecDateTime  TempOut  HiTempOut  \
0                   2             5 2016-12-05 22:50:00      685        685   
1                   2             4 2016-12-05 23:00:00      689        691   
2                   2             5 2016-12-05 23:00:00      685        685   
3                   2             4 2016-12-05 23:10:00      689        689   
4                   2             5 2016-12-05 23:10:00      685        685   
...               ...           ...                 ...      ...        ...   
259021              2             5 2019-06-24 10:30:00      719        719   
259022              2             4 2019-06-24 10:40:00    32767     -32768   
259023              2             5 2019-06-24 10:40:00      722        722   
259024              2             4 2019-06-24 10:50:00    32767     -32768   
259025              2             5 2019-06-24 10:50:00      728        728   

        LowTempOut  HumOut  DewPoint  HeatIndex  IntervalIndex  
0              684      36       403        660              0  
1              689       0     32767      32767              0  
2              684      36       403        660              0  
3              689       0     32767      32767              0  
4              684      36       403        660              0  
...            ...     ...       ...        ...            ...  
259021         716      70       616        730              0  
259022       32767       0     32767      32767              0  
259023         719      71       623        730              0  
259024       32767       0     32767      32767              0  
259025         722      72       632        740              0  

[259026 rows x 10 columns]

df_Receivers container the locations of the receiver

In [145]:
df_Receivers = pd.read_csv(os.path.join(Klimadaten_Wetterstation,"Wetterstation_2016.12.05-2019.06.24","Receivers.txt"), header = 1,sep=",",encoding= 'unicode_escape')
df_Receivers

ReceiverRecID         ReceiverName             ReceiverLoc  Elevation  \
0              2  'Envoy8x Schuetzen'  'Schuetzen am Gebirge'       1198   

   Latitude  Longitude  TimeZone  DSNow  IntervalIndex HWRev   FWRev BWRev  \
0      47.8       16.6        22      0              8    ''  '3.14'    ''   

   ReceiverType  Settings  
0             0         1

df_channels container the informations of the channels

In [105]:
df_channels = pd.read_csv(os.path.join(Klimadaten_Wetterstation,"Wetterstation_2016.12.05-2019.06.24","Channels.txt"), header = 1,sep=",",encoding= 'unicode_escape')
df_channels = pl.DataFrame(df_channels)
df_channels

shape: (4, 8)
┌────────────┬────────────┬───────────┬───────────┬──────────┬────────────┬────────────┬──────────┐
│ ReceiverRe ┆ ChannelInd ┆ ChannelNa ┆ ChannelTy ┆ Repeater ┆ RainCollec ┆ RainCollec ┆ Settings │
│ cID        ┆ ex         ┆ me        ┆ pe        ┆ ---      ┆ torType    ┆ torInc     ┆ ---      │
│ ---        ┆ ---        ┆ ---       ┆ ---       ┆ i64      ┆ ---        ┆ ---        ┆ i64      │
│ i64        ┆ i64        ┆ str       ┆ i64       ┆          ┆ i64        ┆ f64        ┆          │
╞════════════╪════════════╪═══════════╪═══════════╪══════════╪════════════╪════════════╪══════════╡
│ 2          ┆ 3          ┆ 'Envoy8x  ┆ 6         ┆ 0        ┆ 1          ┆ 0.007874   ┆ 0        │
│            ┆            ┆ Schuetzen ┆           ┆          ┆            ┆            ┆          │
│            ┆            ┆ /Vantage  ┆           ┆          ┆            ┆            ┆          │
│            ┆            ┆ Pro2 ...  ┆           ┆          ┆            ┆            ┆          │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 2          ┆ 4          ┆ 'Envoy8x  ┆ 1         ┆ 0        ┆ 255        ┆ 0.0        ┆ 0        │
│            ┆            ┆ Schuetzen ┆           ┆          ┆            ┆            ┆          │
│            ┆            ┆ /Temperat ┆           ┆          ┆            ┆            ┆          │
│            ┆            ┆ ure_5...  ┆           ┆          ┆            ┆            ┆          │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 2          ┆ 5          ┆ 'Envoy8x  ┆ 3         ┆ 0        ┆ 255        ┆ 0.0        ┆ 0        │
│            ┆            ┆ Schuetzen ┆           ┆          ┆            ┆            ┆          │
│            ┆            ┆ /Temperat ┆           ┆          ┆            ┆            ┆          │
│            ┆            ┆ ure/H...  ┆           ┆          ┆            ┆            ┆          │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 2          ┆ 8          ┆ 'Envoy8x  ┆ 16        ┆ 0        ┆ 255        ┆ 0.0        ┆ 0        │
│            ┆            ┆ Schuetzen ┆           ┆          ┆            ┆            ┆          │
│            ┆            ┆ /Inside   ┆           ┆          ┆            ┆            ┆          │
│            ┆            ┆ Data'     ┆           ┆          ┆            ┆            ┆          │
└────────────┴────────────┴───────────┴───────────┴──────────┴────────────┴────────────┴──────────┘

In [147]:
# Join tables

df_diagnosticData.columns = [w + "_D" if w != "RecDateTime" else w for w in df_diagnosticData.columns]
df_Inside.columns = [w + "_I" if w != "RecDateTime" else w for w in df_Inside.columns]
df_ISSData.columns = [w + "_ISS" if w != "RecDateTime" else w for w in df_ISSData.columns]
df_TempHumData.columns = [w + "_T" if w != "RecDateTime" else w for w in df_TempHumData.columns]

In [148]:
df_diagnosticData = pl.DataFrame(df_diagnosticData)
df_Inside = pl.DataFrame(df_Inside)
df_ISSData = pl.DataFrame(df_ISSData)
df_TempHumData = pl.DataFrame(df_TempHumData)

In [170]:
df = df_diagnosticData.join_asof(df_Inside, on="RecDateTime", by="RecDateTime")
df = df.join_asof(df_ISSData, on="RecDateTime", by="RecDateTime")
df = df.join_asof(df_TempHumData, on="RecDateTime", by="RecDateTime")
df = df.drop(["ReceiverRecID_I","ReceiverRecID_T","ReceiverRecID_ISS","IntervalIndex_D","IntervalIndex_I","IntervalIndex_ISS","IntervalIndex_T"])
df

shape: (388539, 51)
┌────────────┬────────────┬───────────┬────────────┬─────┬────────────┬──────────┬──────────┬───────────┐
│ ReceiverRe ┆ ChannelInd ┆ RecDateTi ┆ PacketsRec ┆ ... ┆ LowTempOut ┆ HumOut_T ┆ DewPoint ┆ HeatIndex │
│ cID_D      ┆ ex_D       ┆ me        ┆ eived_D    ┆     ┆ _T         ┆ ---      ┆ _T       ┆ _T        │
│ ---        ┆ ---        ┆ ---       ┆ ---        ┆     ┆ ---        ┆ i64      ┆ ---      ┆ ---       │
│ i64        ┆ i64        ┆ datetime[ ┆ i64        ┆     ┆ i64        ┆          ┆ i64      ┆ i64       │
│            ┆            ┆ ns]       ┆            ┆     ┆            ┆          ┆          ┆           │
╞════════════╪════════════╪═══════════╪════════════╪═════╪════════════╪══════════╪══════════╪═══════════╡
│ 2          ┆ 5          ┆ 2016-12-0 ┆ 166        ┆ ... ┆ 690        ┆ 36       ┆ 408      ┆ 660       │
│            ┆            ┆ 5         ┆            ┆     ┆            ┆          ┆          ┆           │
│            ┆            ┆ 18:00:00  ┆            ┆     ┆            ┆          ┆          ┆           │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 2          ┆ 3          ┆ 2016-12-0 ┆ 164        ┆ ... ┆ 690        ┆ 36       ┆ 409      ┆ 660       │
│            ┆            ┆ 5         ┆            ┆     ┆            ┆          ┆          ┆           │
│            ┆            ┆ 18:10:00  ┆            ┆     ┆            ┆          ┆          ┆           │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 2          ┆ 4          ┆ 2016-12-0 ┆ 167        ┆ ... ┆ 690        ┆ 36       ┆ 409      ┆ 660       │
│            ┆            ┆ 5         ┆            ┆     ┆            ┆          ┆          ┆           │
│            ┆            ┆ 18:10:00  ┆            ┆     ┆            ┆          ┆          ┆           │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 2          ┆ 5          ┆ 2016-12-0 ┆ 158        ┆ ... ┆ 690        ┆ 36       ┆ 409      ┆ 660       │
│            ┆            ┆ 5         ┆            ┆     ┆            ┆          ┆          ┆           │
│            ┆            ┆ 18:10:00  ┆            ┆     ┆            ┆          ┆          ┆           │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ ...        ┆ ...        ┆ ...       ┆ ...        ┆ ... ┆ ...        ┆ ...      ┆ ...      ┆ ...       │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 2          ┆ 5          ┆ 2019-06-2 ┆ 200        ┆ ... ┆ 719        ┆ 71       ┆ 623      ┆ 730       │
│            ┆            ┆ 4         ┆            ┆     ┆            ┆          ┆          ┆           │
│            ┆            ┆ 10:40:00  ┆            ┆     ┆            ┆          ┆          ┆           │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 2          ┆ 3          ┆ 2019-06-2 ┆ 218        ┆ ... ┆ 722        ┆ 72       ┆ 632      ┆ 740       │
│            ┆            ┆ 4         ┆            ┆     ┆            ┆          ┆          ┆           │
│            ┆            ┆ 10:50:00  ┆            ┆     ┆            ┆          ┆          ┆           │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 2          ┆ 4          ┆ 2019-06-2 ┆ 0          ┆ ... ┆ 722        ┆ 72       ┆ 632      ┆ 740       │
│            ┆            ┆ 4         ┆            ┆     ┆            ┆          ┆          ┆           │
│            ┆            ┆ 10:50:00  ┆            ┆     ┆            ┆          ┆          ┆           │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 2          ┆ 5          ┆ 2019-06-2 ┆ 198        ┆ ... ┆

In [171]:
df.write_csv(os.path.join(Klimadaten_Wetterstation,"Wetterstation_2016.12.05-2019.06.24","data.csv"))

## Suhlenlogger

In [4]:
files_suhlenlogger = os.listdir(path_Suhlenlogger)
files_suhlenlogger_1 = [w for w in files_suhlenlogger if "Suhle1" in w]
files_suhlenlogger_2 = [w for w in files_suhlenlogger if "Suhle2" in w]
files_suhlenlogger_3 = [w for w in files_suhlenlogger if "Suhle3" in w]
files_suhlenlogger_4 = [w for w in files_suhlenlogger if "Suhle4" in w]
files_suhlenlogger_5 = [w for w in files_suhlenlogger if "Suhle5" in w]
files_suhlenlogger_6 = [w for w in files_suhlenlogger if "Suhle6" in w]
files_suhlenlogger_7 = [w for w in files_suhlenlogger if "Suhle7" in w]
files_suhlenlogger_8 = [w for w in files_suhlenlogger if "Suhle8" in w]
files_suhlenlogger_9 = [w for w in files_suhlenlogger if "Suhle9" in w]
files_suhlenlogger_FG = [w for w in files_suhlenlogger if "SuhleFG" in w]
files_suhlenlogger_VG = [w for w in files_suhlenlogger if "SuhleVG" in w]

In [48]:
list_names = ["Suhlen1","Suhlen2","Suhlen3","Suhlen4","Suhlen5","Suhlen6","Suhlen7","Suhlen8","Suhlen9","SuhlenFG","SuhlenVG"]
lists = [files_suhlenlogger_1,files_suhlenlogger_2,files_suhlenlogger_3,files_suhlenlogger_4,files_suhlenlogger_5,files_suhlenlogger_6,files_suhlenlogger_7,files_suhlenlogger_8,files_suhlenlogger_9,files_suhlenlogger_FG,files_suhlenlogger_VG]
for index,name in enumerate(list_names):
    result = pd.DataFrame()
    list_data = []
    for file in lists[index]:
        try:
            df = pd.read_csv(os.path.join(path_Suhlenlogger,file), skiprows=13, sep=",",encoding= 'unicode_escape')
            cont = 0
            list = []
            with open(os.path.join(path_Suhlenlogger,file)) as file_obj:
                
                reader_obj = csv.reader(file_obj)
            
                for row in reader_obj:
                    list.append(row[0])
                    if cont == 12:
                        break
                    cont += 1
            
            df["Date/Time"] = pd.to_datetime(df["Date/Time"])
            
            result = pd.concat([result,df.iloc[:,:]])
            list_data.append(list)
        except:
            df = pd.read_csv(os.path.join(path_Suhlenlogger,file), skiprows=18, sep=",",encoding= 'unicode_escape')
            cont = 0
            list = []
            with open(os.path.join(path_Suhlenlogger,file)) as file_obj:
                
                reader_obj = csv.reader(file_obj)
            
                for row in reader_obj:
                    list.append(row[0])
                    if cont == 17:
                        break
                    cont += 1
            
            df["Date/Time"] = pd.to_datetime(df["Date/Time"])
            
            result = pd.concat([result,df.iloc[:,:]])
            list_data.append(list)
    
    with open(os.path.join(path_Suhlenlogger,name + "_summary.csv"), 'w') as f:
        write = csv.writer(f)
        write.writerows(list_data)
    
    result = result.reset_index(drop=True)
    result.to_csv(os.path.join(path_Suhlenlogger, name + ".csv"),index=False)

## Telemetriedate

In [12]:
Telemetriedate_acceleration = os.path.join(path_Telemetriedate, "acceleration")
Telemetriedate_positions = os.path.join(path_Telemetriedate, "positions")
Telemetriedate_rssi = os.path.join(path_Telemetriedate, "rssi")
Telemetriedate_temperatures = os.path.join(path_Telemetriedate, "temperatures")

### acceleration

- Tagid
- Tagmac

Small areas or big areas ?
Which kind of will boars ?

In [17]:
acceleration_files = os.listdir(Telemetriedate_acceleration)
init = datetime(int(acceleration_files[1][:4]), int(acceleration_files[1][4:6]), int(acceleration_files[1][6:8]))
end = datetime(int(acceleration_files[-1][:4]), int(acceleration_files[-1][4:6]), int(acceleration_files[-1][6:8]))
print(init)
print(end)

2016-12-20 00:00:00
2020-02-10 00:00:00


In [38]:
df = pd.read_csv(os.path.join(Telemetriedate_acceleration,acceleration_files[1]),sep=";")
df["timestampms"] = pd.to_datetime(df["timestampms"],format="%Y%m%d%H%M%S%f")
df = df.drop(["animalname"], axis=1)
df

timestampms tagid  tagmac  modulversion  softwareversion  \
0     2016-12-20 13:12:43.708     2  151069          75.0             67.0   
1     2016-12-20 13:12:44.263     1  113308          75.0             64.0   
2     2016-12-20 13:12:44.708     2  151069          75.0             67.0   
3     2016-12-20 13:12:45.263     1  113308          75.0             64.0   
4     2016-12-20 13:12:45.708     2  151069          75.0             67.0   
...                       ...   ...     ...           ...              ...   
19665 2016-12-20 13:28:39.063    34  148437          75.0             67.0   
19666 2016-12-20 13:28:39.106    70  156011          75.0             66.0   
19667 2016-12-20 13:28:39.163    34  148437          75.0             67.0   
19668 2016-12-20 13:28:39.263    34  148437          75.0             67.0   
19669 2016-12-20 13:28:39.470   21D     541           NaN              NaN   

       accX  accY  accZ  absoluteAcc  
0       -16   864   480      988.510  
1        80   336 -1024     1080.681  
2       -16   880   480     1002.525  
3        80   320 -1008     1060.596  
4       -16   864   464      980.840  
...     ...   ...   ...          ...  
19665    32  -896   432      995.221  
19666   -32   800   640     1025.000  
19667    32  -896   416      988.380  
19668    32  -912   432     1009.649  
19669   -16   -20  1024     1024.320  

[19670 rows x 9 columns]

### Positions

In [39]:
position_files = os.listdir(Telemetriedate_positions)
init = datetime(int(position_files[1][:4]), int(position_files[1][4:6]), int(position_files[1][6:8]))
end = datetime(int(position_files[-1][:4]), int(position_files[-1][4:6]), int(position_files[-1][6:8]))
print(init)
print(end)

2017-01-26 00:00:00
2020-02-10 00:00:00


In [40]:
df = pd.read_csv(os.path.join(Telemetriedate_positions,position_files[1]),sep=";")
df["timestampms"] = pd.to_datetime(df["timestampms"],format="%Y%m%d%H%M%S%f")
df = df.drop(["animalname"], axis=1)
df

timestampms  tagid  tagmac  modulversion  softwareversion  \
0     2017-01-26 21:03:11.082      2  151069           9.3              8.3   
1     2017-01-26 21:03:11.371     72  136194           9.3              8.2   
2     2017-01-26 21:03:11.586     93  162438           9.3              8.3   
3     2017-01-26 21:03:12.174     97  155604           9.3              8.3   
4     2017-01-26 21:03:12.347     45  147610           9.3              8.2   
...                       ...    ...     ...           ...              ...   
27396 2017-01-26 23:59:59.756     21  142741           9.3              8.2   
27397 2017-01-26 23:59:59.842     60  167155           9.3              8.2   
27398 2017-01-26 23:59:59.865     73  141216           9.3              8.2   
27399 2017-01-26 23:59:59.912     34  148437           9.3              8.3   
27400 2017-01-26 23:59:59.958      2  151069           9.3              8.3   

       x-value  y-value  Unnamed: 8  
0            0        0         NaN  
1            0        0         NaN  
2            0        0         NaN  
3            0        0         NaN  
4            0        0         NaN  
...        ...      ...         ...  
27396        0        0         NaN  
27397        0        0         NaN  
27398        0        0         NaN  
27399        0        0         NaN  
27400        0        0         NaN  

[27401 rows x 8 columns]

### Rssi


In [45]:
rssi_files = os.listdir(Telemetriedate_rssi)
init = datetime(int(rssi_files[1][:4]), int(rssi_files[1][4:6]), int(rssi_files[1][6:8]))
end = datetime(int(rssi_files[-1][:4]), int(rssi_files[-1][4:6]), int(rssi_files[-1][6:8]))
print(init)
print(end)

2016-12-20 00:00:00
2020-02-10 00:00:00


In [54]:
df = pd.read_csv(os.path.join(Telemetriedate_rssi,rssi_files[1]),sep=";")
df["timestamp"] = pd.to_datetime(df["timestamp"],format="%Y%m%d%H%M%S%f")
df

timestamp  tagmac  anchor  rssi  anchor.1  rssi.1  \
0    2016-12-20 13:12:56.211  155786      64   7.0      64.0     8.0   
1    2016-12-20 13:12:57.199  155786      64   6.0      64.0     8.0   
2    2016-12-20 13:12:57.871     541      64   5.0      64.0     2.0   
3    2016-12-20 13:12:58.187  155786      64   7.0      64.0     7.0   
4    2016-12-20 13:12:58.647  148437      64   7.0       NaN     NaN   
...                      ...     ...     ...   ...       ...     ...   
2035 2016-12-20 13:28:37.903  127555      64   5.0      64.0     1.0   
2036 2016-12-20 13:28:38.781  155786      64   9.0      64.0     8.0   
2037 2016-12-20 13:28:39.106  156011      64   2.0      64.0     1.0   
2038 2016-12-20 13:28:39.263  148437      64   7.0      64.0    13.0   
2039 2016-12-20 13:28:39.470     541      64   6.0      64.0     1.0   

      anchor.2  rssi..  
0          NaN     NaN  
1          NaN     NaN  
2          NaN     NaN  
3          NaN     NaN  
4          NaN     NaN  
...        ...     ...  
2035       NaN     NaN  
2036       NaN     NaN  
2037       NaN     NaN  
2038       NaN     NaN  
2039       NaN     NaN  

[2040 rows x 8 columns]

### Temperatures

In [13]:
Telemetriedate_temperatures

'../Wildschwein_Eisenstadt/Telemetriedaten/temperatures'

In [55]:
temp_files = os.listdir(Telemetriedate_temperatures)
init = datetime(int(temp_files[1][:4]), int(temp_files[1][4:6]), int(temp_files[1][6:8]))
end = datetime(int(temp_files[-1][:4]), int(temp_files[-1][4:6]), int(temp_files[-1][6:8]))
print(init)
print(end)

2016-12-20 00:00:00
2020-02-10 00:00:00


In [58]:
df = pd.read_csv(os.path.join(Telemetriedate_temperatures,temp_files[1]),sep=";")
df["timestampms"] = pd.to_datetime(df["timestampms"],format="%Y%m%d%H%M%S%f")
df = df.drop(["animalname"], axis=1)
df

timestampms  tagid  tagmac  temperature
0  2016-12-20 13:13:10.075   58.0  155786        24.50
1  2016-12-20 13:13:24.398   62.0  121996        22.50
2  2016-12-20 13:13:30.317    2.0  151069        24.25
3  2016-12-20 13:13:32.511   29.0  127555        24.00
4  2016-12-20 13:13:33.413    NaN     541        27.75
..                     ...    ...     ...          ...
94 2016-12-20 13:28:10.584   62.0  121996        22.75
95 2016-12-20 13:28:16.541    2.0  151069        24.25
96 2016-12-20 13:28:22.041   29.0  127555        24.25
97 2016-12-20 13:28:34.821    1.0  164820        24.00
98 2016-12-20 13:28:36.491   34.0  148437        24.25

[99 rows x 4 columns]

## Temperaturlogger

In [29]:
files = os.listdir(os.path.join(path_Temperaturlogger))
files = [w for w in files if ".csv" in w and not "comp" in w]

In [42]:
id = []
id_name = {}
for w in files:
    df = pd.read_csv(os.path.join(path_Temperaturlogger,w),sep=",")
    id.append(int(df.iloc[0,0]))
    id_name[w] = int(df.iloc[0,0])
id.sort()

In [ ]:
# Longitud de 92 diferentes id
print(id)
# [2, 3, 3, 5, 5, 6, 7, 7, 8, 8, 9, 9, 12, 18, 19, 20, 21, 22, 25, 25, 26, 28, 29, 30, 31, 32, 32, 34, 35, 37, 38, 39, 40, 57, 58, 59, 60, 
# 67, 70, 102, 103, 103, 104, 104, 105, 105, 106, 107, 107, 108, 108, 109, 109, 110, 112, 113, 113, 113, 113, 114, 116, 118, 119, 119, 120,
# 121, 122, 125, 125, 126, 128, 129, 130, 131, 132, 132, 133, 134, 135, 136, 137, 140, 143, 145, 157, 158, 160, 167, 170, 183, 185, 187]

In [44]:
id_name

{'if_2016_DE.2011.25.csv': 108,
 'if_2017_IS.2011.02.csv': 143,
 'if_2017_JG.2010.01.csv': 183,
 'if_2017_JG.2011.07.csv': 185,
 'if_2017_JG.2012.09.csv': 145,
 'if_2017_JG.2015.02.csv': 187,
 'ip_2016_DE.2011.14.csv': 116,
 'ip_2016_DE.2011.23.csv': 103,
 'ip_2016_DE.2011.27.csv': 104,
 'ip_2016_IS.2011.02.csv': 112,
 'ip_2016_IS.2011.04.csv': 113,
 'ip_2016_IS.2011.05.csv': 114,
 'ip_2016_IS.2011.13.csv': 102,
 'ip_2016_IS.2011.15.csv': 118,
 'ip_2016_IS.2011.16.csv': 113,
 'ip_2016_IS.2011.24.csv': 105,
 'ip_2016_IS.2011.25.csv': 109,
 'ip_2016_IS.2011.26.csv': 106,
 'ip_2016_IS.2011.32.csv': 120,
 'ip_2016_IS.2011.34.csv': 119,
 'ip_2016_IS.2011.38.csv': 107,
 'ip_2016_IS.2011.39.csv': 110,
 'ip_2016_JG.2009.01.csv': 121,
 'ip_2016_JG.2011.03.csv': 130,
 'ip_2016_JG.2011.04.csv': 133,
 'ip_2016_JG.2011.05.csv': 137,
 'ip_2016_JG.2012.01.csv': 126,
 'ip_2016_JG.2012.03.csv': 131,
 'ip_2016_JG.2012.04.csv': 132,
 'ip_2016_JG.2012.05.csv': 134,
 'ip_2016_JG.2012.06.csv': 136,
 'ip_201

In [10]:
if_temp = [w for w in files if "if" in w]
ip_temp = [w for w in files if "ip" in w]
sc_temp = [w for w in files if "sc" in w]

DE.2011.25 if is if is 108 id and if is sc is 8 ? what this mean?

In [14]:
if_temp[0]

'if_2016_DE.2011.25.csv'

In [13]:
df = pd.read_csv(os.path.join(path_Temperaturlogger,if_temp[0]),sep=",")
df

Id                 Date  RawData  Temperature
0       108  2016-09-26 14:33:00      409        25.33
1       108  2016-09-26 14:37:00      403        24.95
2       108  2016-09-26 14:41:00      402        24.89
3       108  2016-09-26 14:45:00      400        24.77
4       108  2016-09-26 14:49:00      399        24.70
...     ...                  ...      ...          ...
135987  108  2017-10-09 08:21:00      372        23.02
135988  108  2017-10-09 08:25:00      373        23.08
135989  108  2017-10-09 08:29:00        0        -0.14
135990  108  2017-10-09 08:33:00        0        -0.14
135991  108  2017-10-09 08:37:00        0        -0.14

[135992 rows x 4 columns]

In [17]:
ip_temp[0]

'ip_2016_DE.2011.14.csv'

In [15]:
df = pd.read_csv(os.path.join(path_Temperaturlogger,ip_temp[0]),sep=",")
df

Id                 Date  RawData  Temperature
0       116  2016-09-29 09:50:00      414        25.72
1       116  2016-09-29 09:54:00      412        25.60
2       116  2016-09-29 09:58:00      484        30.06
3       116  2016-09-29 10:02:00      523        32.48
4       116  2016-09-29 10:06:00      551        34.22
...     ...                  ...      ...          ...
137507  116  2017-10-16 08:58:00      386        23.98
137508  116  2017-10-16 09:02:00      395        24.54
137509  116  2017-10-16 09:06:00        0         0.04
137510  116  2017-10-16 09:10:00        0         0.04
137511  116  2017-10-16 09:14:00        0         0.04

[137512 rows x 4 columns]

In [18]:
sc_temp[0]

'sc_2016_DE.2011.23.csv'

In [19]:
df = pd.read_csv(os.path.join(path_Temperaturlogger,sc_temp[0]),sep=",")
df

Id                 Date  RawData  Temperature
0        3  2016-09-26 14:18:00      406        25.16
1        3  2016-09-26 14:22:00      407        25.22
2        3  2016-09-26 14:26:00      407        25.22
3        3  2016-09-26 14:30:00      406        25.16
4        3  2016-09-26 14:34:00      405        25.10
...     ..                  ...      ...          ...
136339   3  2017-10-10 07:34:00      348        21.57
136340   3  2017-10-10 07:38:00      358        22.19
136341   3  2017-10-10 07:42:00      358        22.19
136342   3  2017-10-10 07:46:00      362        22.43
136343   3  2017-10-10 07:50:00      360        22.31

[136344 rows x 4 columns]

### Originale von Gerhard, termo logger

I remover file "sc_2017_IS.2011.13_i1.csv"

In [35]:
original_temp = os.path.join(path_Temperaturlogger,"Originale von Gerhard")
original_temp_file = [w for w in os.listdir(original_temp) if ".csv" in w]

In [43]:
id_orig = []
id_orig_name = {}
for w in original_temp_file:
    df = pd.read_csv(os.path.join(original_temp,w),sep=",")
    id_orig.append(int(df.iloc[0,0]))
    id_orig_name[w] = int(df.iloc[0,0])
id_orig.sort()

In [39]:
#longitud 97
print(id_orig)
# [2, 3, 3, 5, 5, 6, 7, 7, 8, 8, 9, 9, 12, 18, 19, 20, 21, 22, 23, 25, 25, 26, 27, 28, 29, 30, 31, 32, 32, 34, 35, 37, 38, 39, 39, 40, 40, 57, 58, 59, 60,
#  67, 70, 102, 103, 103, 104, 104, 105, 105, 106, 107, 107, 108, 108, 109, 109, 110, 112, 113, 113, 114, 116, 118, 119, 119, 120,
#  121, 122, 125, 125, 126, 127, 128, 129, 130, 131, 132, 132, 133, 134, 135, 136, 137, 139, 140, 140, 143, 145, 157, 158, 160, 167, 170, 183, 185, 187]

[2, 3, 3, 5, 5, 6, 7, 7, 8, 8, 9, 9, 12, 18, 19, 20, 21, 22, 23, 25, 25, 26, 27, 28, 29, 30, 31, 32, 32, 34, 35, 37, 38, 39, 39, 40, 40, 57, 58, 59, 60, 67, 70, 102, 103, 103, 104, 104, 105, 105, 106, 107, 107, 108, 108, 109, 109, 110, 112, 113, 113, 114, 116, 118, 119, 119, 120, 121, 122, 125, 125, 126, 127, 128, 129, 130, 131, 132, 132, 133, 134, 135, 136, 137, 139, 140, 140, 143, 145, 157, 158, 160, 167, 170, 183, 185, 187]


In [29]:
name = original_temp_file[0][12:-4]
print(name)
df = pd.read_csv(os.path.join(original_temp,original_temp_file[0]),sep=",")
df 

ID102


Id                 Date  RawData  Temperature
0       102  2016-09-26 14:59:00      416        25.84
1       102  2016-09-26 15:03:00      413        25.66
2       102  2016-09-26 15:07:00      409        25.41
3       102  2016-09-26 15:11:00      406        25.22
4       102  2016-09-26 15:15:00      404        25.10
...     ...                  ...      ...          ...
136335  102  2017-10-10 07:59:00      360        22.37
136336  102  2017-10-10 08:03:00      363        22.56
136337  102  2017-10-10 08:07:00      360        22.37
136338  102  2017-10-10 08:11:00      355        22.06
136339  102  2017-10-10 08:15:00      361        22.43

[136340 rows x 4 columns]

In [ ]:
# [2, 3, 3, 5, 5, 6, 7, 7, 8, 8, 9, 9, 12, 18, 19, 20, 21, 22, 25, 25, 26, 28, 29, 30, 31, 32, 32, 34, 35, 37, 38, 39, 40, 57, 58, 59, 60, 67, 70, 102, 103, 103, 104, 104, 105, 105, 106, 107, 107, 108, 108, 109, 109, 110, 112, 113, 113, 113, 113, 114, 116, 118, 119, 119, 120, 121, 122, 125, 125, 126, 128, 129, 130, 131, 132, 132, 133, 134, 135, 136, 137, 140, 143, 145, 157, 158, 160, 167, 170, 183, 185, 187]

# [2, 3, 3, 5, 5, 6, 7, 7, 8, 8, 9, 9, 12, 18, 19, 20, 21, 22, 23, 25, 25, 26, 27, 28, 29, 30, 31, 32, 32, 34, 35, 37, 38, 39, 39, 40, 40, 57, 58, 59, 60, 67, 70, 102, 103, 103, 104, 104, 105, 105, 106, 107, 107, 108, 108, 109, 109, 110, 112, 113, 113, 114, 116, 118, 119, 119, 120, 121, 122, 125, 125, 126, 127, 128, 129, 130, 131, 132, 132, 133, 134, 135, 136, 137, 139, 140, 140, 143, 145, 157, 158, 160, 167, 170, 183, 185, 187]

# Diferentes
# 23, 27, 39, 40, 113, 113, 127, 139, 140

normal files, if/ip/sc + tagmac : inside put the id type
original file, id

The two files are the same, except 23, 27, 39, 40, 113, 113, 113, 127, 139, 140 which are not in the other files.

- Put in the name, id + tagmac ?
- Inside the file, add if/ip/sc and the tagmac

2 options

- Do not take these files
- Join the files with the same id and assume they are ip/sc

Fichero

../Wildschwein_Eisenstadt/Wichtige Projektfiles/Tiere/ImplantedAnimals.xlsx

Nos dice que Id es para cada uno de los if/ip/sc

## Wichtige Projektfiles

### binary data

In [45]:
binary_data = os.path.join(path_Wichtige_Projektfiles,"binary data")
binary_data_files = os.listdir(binary_data)
binary_data_files = [file for file in binary_data_files if ".RData" in file]
binary_data_files

['Accelerationdata.RData',
 'Accelerationdata_2016.RData',
 'Accelerationdata_2017.RData',
 'Positionsdata_2017.RData',
 'Positionsdata_2018.RData',
 'Positionsdata_2019.RData']

In [ ]:
# result = rdata.parser.parse_file(os.path.join(binary_data,"Loggers and Climate_one dataframe_closest time.RData")) # also works for Rds
# df = rdata.conversion.convert(result)
# df["AllData"]
# df["AllData"].to_csv(os.path.join(binary_data,"Loggers and Climate_one dataframe_closest time.csv"))

In [46]:
logg_climate = os.path.join(binary_data,"Loggers and Climate_one dataframe_closest time")
logg_climate_aprox = os.path.join(binary_data,"Loggers and Climate_one dataframe_linear approx")
logg_climate_separate = os.path.join(binary_data,"Loggers and Climate_separate dataframes")
tele_fiwi = os.path.join(binary_data,"TelemetrieFiwigatter")
tele_jagd = os.path.join(binary_data,"TelemetrieJagdgatter")
water = os.path.join(binary_data,"WaterTemperatures")

In [ ]:
df_logg_climate = pd.read_csv(os.path.join(logg_climate,"Loggers and Climate_one dataframe_closest time_AllData.csv"),low_memory=False)
df_logg_climate

In [ ]:
df_logg_climate_aprox = pd.read_csv(os.path.join(logg_climate,"Loggers and Climate_one dataframe_linear approx_AllData.approx.csv"))
df_logg_climate_aprox

In [ ]:
files_climate_separate = os.listdir(logg_climate_separate)[1:]
df_EarTemp = pd.read_csv(os.path.join(logg_climate_separate,files_climate_separate[0]))
df_HeartRate = pd.read_csv(os.path.join(logg_climate_separate,files_climate_separate[1]))
df_IntraFixe = pd.read_csv(os.path.join(logg_climate_separate,files_climate_separate[2]))
df_IntraFree = pd.read_csv(os.path.join(logg_climate_separate,files_climate_separate[3]))
df_OL = pd.read_csv(os.path.join(logg_climate_separate,files_climate_separate[4]))
df_Subcut = pd.read_csv(os.path.join(logg_climate_separate,files_climate_separate[5]),low_memory=False)
df_Telemetrie = pd.read_csv(os.path.join(logg_climate_separate,files_climate_separate[6]))
df_Weather = pd.read_csv(os.path.join(logg_climate_separate,files_climate_separate[7]))

### Daten Abschuss 2020

In [24]:
date_abschuss = os.path.join(path_Wichtige_Projektfiles,"Daten Abschuss 2020")
date_abschuss_files = os.listdir(date_abschuss)
date_abschuss_files

['FiWi_Gatter_Abschuss_2020.xlsx',
 'FiWi_Gatter_Abschuss_2020_2.xlsx',
 'FiWi_Gatter_Abschuss_2020_3.xlsx',
 'FiWi_Gatter_Abschuss_2020_all.xlsx']

This date, are from the date 3/1/2020 to 27/1 i dont know if is usefull

### FutterWasser

In [25]:
date_futterWasser = os.path.join(path_Wichtige_Projektfiles,"FutterWasser")
date_futterWasser_files = os.listdir(date_futterWasser)
date_futterWasser_files

['Futterautomaten JG.xlsx',
 'Futterübersicht aktuell.xlsx',
 'Mastaufnahme.xlsx',
 'Suhlenlogger.xlsx',
 'ZusammenfassungWasserqualität.xlsx']

In [34]:
#Of the food, will be important
df_Futterübersicht_1 = pd.read_excel(os.path.join(date_futterWasser,"Futterübersicht aktuell.xlsx"),sheet_name='Futterliste')

df_Futterübersicht_2 = pd.read_excel(os.path.join(date_futterWasser,"Futterübersicht aktuell.xlsx"),sheet_name='Auswertungen und Grafiken')
df_Futterübersicht_2 = df_Futterübersicht_2.iloc[:150,12:]

In [36]:
df_Mastaufnahme = pd.read_excel(os.path.join(date_futterWasser,"Mastaufnahme.xlsx"),sheet_name='alle Rohdaten')

In [37]:
df_Suhlenlogger = pd.read_excel(os.path.join(date_futterWasser,"Suhlenlogger.xlsx"), sheet_name="Auslesen")

In [38]:
df_ZusammenfassungWasserqualität = pd.read_excel(os.path.join(date_futterWasser,"ZusammenfassungWasserqualität.xlsx"),sheet_name="Tabelle1")

### Telemetrie

In [50]:
date_telemetrie = os.path.join(path_Wichtige_Projektfiles,"Telemetrie")
date_telemetrie_files = [file for file in os.listdir(date_telemetrie) if not ".pdf" in file ]
date_telemetrie_files

['IDs Smartbowmarken.csv',
 'Smartbowmarken IDs.xlsx',
 'TelemetrieAnimals.xlsx',
 'TelemetrieEmpfänger.csv',
 'TelemetrieEmpfänger.xlsx']

In [48]:
df_ids = pd.read_csv(os.path.join(date_telemetrie,"IDs Smartbowmarken.csv"))
df_smart = pd.read_excel(os.path.join(date_telemetrie,"Smartbowmarken IDs.xlsx"))
df_teleanimals = pd.read_excel(os.path.join(date_telemetrie,"TelemetrieAnimals.xlsx")).iloc[:103,:]
df_tele = pd.read_csv(os.path.join(date_telemetrie,"TelemetrieEmpfänger.csv"), sep=",",encoding= 'unicode_escape')

### Tiere

In [48]:
date_tiere = os.path.join(path_Wichtige_Projektfiles,"Tiere")
date_tiere_files = os.listdir(date_tiere)
date_tiere_files

['Abschussliste FiWi_Gatter.xlsx',
 'Anzahl Tiere Gatter Verlauf.xlsx',
 'ImplantedAnimals.xlsx',
 'Masterfile Reproduction.xlsx',
 'MasterfileTiere.xlsx',
 'MicrosatDaten ProjektEsterhazy.xlsx',
 'Missing Implanted Animals.xlsx',
 'OverviewLogger.csv',
 'OverviewLogger.xlsx',
 'OverviewLogger_CB.xlsx',
 'UebersichtHeartrateLogger.xlsx',
 '~$OverviewLogger.xlsx']

In [49]:
os.path.join(date_tiere,"OverviewLogger.xlsx")

'../Wildschwein_Eisenstadt/Wichtige Projektfiles/Tiere/OverviewLogger.xlsx'

In [56]:
df_imp = pd.read_excel(os.path.join(date_tiere,"ImplantedAnimals.xlsx"))
df_repro = pd.read_excel(os.path.join(date_tiere,"Masterfile Reproduction.xlsx"))
df_tiere = pd.read_excel(os.path.join(date_tiere,"MasterfileTiere.xlsx")) # Une id con tag
df_over = pd.read_excel(os.path.join(date_tiere,"OverviewLogger.xlsx")) # Une id con tag

## Juntar ficheros

../Wildschwein_Eisenstadt/Wichtige Projektfiles/Telemetrie/Smartbowmarken IDs.xlsx

    - nombres tipo gr02 a FG.2016.05 tambien el tipo si es VG o FG

../Wildschwein_Eisenstadt/Wichtige Projektfiles/Telemetrie/TelemetrieAnimals.xlsx 

    - Si dispone de localizador

../Wildschwein_Eisenstadt/Wichtige Projektfiles/Telemetrie/TelemetrieEmpfänger.xlsx

    - Nombre y abreviacion de las zonas, no esta la localizacion

../ImplantedAnimals.xlsx

    - Nos dice que id de teleme es if / ip / sc

../Wildschwein_Eisenstadt/Wichtige Projektfiles/Tiere/OverviewLogger.xlsx'

    - En que area esta cada jabali

### Environment

In this part I will join Weather data (VG/FG/Rest), Suhlen, Water ?

In [89]:
path_logger_FG = "../Join/clima/Logger 1 FG.csv"
path_logger_VG = "../Join/clima/Logger 1 VG.csv"
path_wetterstation = "../Join/clima/clima.csv"
path_binary = "../Join/clima/Loggers and Climate_separate dataframes_Weather.csv"

In [90]:
df_FG = pd.read_csv(os.path.join(path_logger_FG))
df_FG["Time"] = pd.to_datetime(df_FG["Time"], infer_datetime_format=True)
#df_FG.iloc[0,0].strftime("%d-%m-%Y %H:%M:%S")

In [95]:
df_VG = pd.read_csv(os.path.join(path_logger_VG))
df_VG["Time"] = pd.to_datetime(df_VG["Time"], infer_datetime_format=True)
df_VG = df_VG.drop(columns=["Serial Number"])

In [148]:
result_FG_VG = pd.merge(df_FG, df_VG, on="Time",suffixes=('_FG', '_VG'))
result_FG_VG.columns = ["Date","°C_FG","hum_FG","dew_p_FG","°C_VG","hum_VG","dew_p_VG"]
result_FG_VG

Date  °C_FG  hum_FG dew_p_FG  °C_VG  hum_VG  dew_p_VG
0     2011-09-24 00:00:00   15.5    76.5     11.4   14.5    78.5      10.8
1     2011-09-24 01:00:00   15.5    77.0     11.5   14.0    81.0      10.8
2     2011-09-24 02:00:00   15.0    80.0     11.6   13.0    83.0      10.2
3     2011-09-24 03:00:00   14.0    83.0     11.2   13.5    80.5      10.2
4     2011-09-24 04:00:00   14.0    80.5     10.7   13.0    85.5      10.6
...                   ...    ...     ...      ...    ...     ...       ...
41868 2017-03-16 09:00:00   12.0    68.0      6.3   11.5    73.0       6.8
41869 2017-03-16 10:00:00   10.5    63.0      3.8   11.5    65.0       5.2
41870 2017-03-16 11:00:00   16.0    52.5      6.3   24.0    42.0      10.3
41871 2017-03-16 12:00:00   17.0    50.5      6.7   21.5    40.5       7.5
41872 2017-03-16 12:00:00   22.0    37.5      6.8   21.5    40.5       7.5

[41873 rows x 7 columns]

In [110]:
df_wet = pd.read_csv(path_wetterstation)[['Date Time ', 'Outside Temperature TX4 (°C)',
       'Outside Humidity TX4 (%)', 'Wind Speed TX4 (k/hr)','Dominant Wind Dir TX4', 'Rain Amount TX4 (mm)', 'Solar Radiation TX4',
       'Outside Temperature TX5 (°C)','Outside Temperature TX6 (°C)', 'Outside Humidity TX6 (%)','Barometric Pressure (mb)']]
df_bin = pd.read_csv(path_binary)[['Date', 'TempMain', 'HumMain', 'Wind', 'WindDir', 'Rain',
       'Solar', 'TempBB', 'TempForest', 'HumForest', 'BaroPressure']]

In [111]:
# Day of the Week ,Date Time

# Outside Temperature TX4 (Â°C), TempMain
# Outside Humidity TX4 (%), HumMain
# Wind Speed TX4 (k/hr), Wind
# Dominant Wind Dir TX4, WindDir
# Rain Amount TX4 (mm), Rain
# Solar Radiation TX4, Solar
# Outside Temperature TX5 (Â°C), TempBB
# Outside Temperature TX6 (Â°C), TempForest
# Outside Humidity TX6 (%), HumForest
# Barometric Pressure (mb) ,BaroPressure

In [135]:
df_wet.columns = ['Date', 'TempMain', 'HumMain', 'Wind', 'WindDir', 'Rain',
       'Solar', 'TempBB', 'TempForest', 'HumForest', 'BaroPressure']
df_wet["Date"] = pd.to_datetime(df_wet["Date"], infer_datetime_format=True)
df_bin["Date"] = pd.to_datetime(df_bin["Date"], infer_datetime_format=True)

In [143]:
df_bin = df_bin[(df_bin["Date"] < "2016-12-11 00:50:00")]

In [146]:
result = pd.concat([df_wet,df_bin])
result.sort_values(by='Date', inplace=True)

#### Join both dataframes 

In [192]:
result_FG_VG_filter = result_FG_VG[(result_FG_VG["Date"] >= "2016-09-30 18:00:00")]
merged = pd.merge(result,result_FG_VG_filter, on='Date', how="outer")

In [191]:
merged.fillna(np.nan, inplace=True)

In [81]:
merged = pd.read_csv("../environment.csv")
merged["Date"] = pd.to_datetime(merged["Date"], infer_datetime_format=True)

#### Suhlen

In [82]:
list_files = ["Suhlen1","Suhlen2","Suhlen3","Suhlen4","Suhlen5","Suhlen6","Suhlen7",\
    "Suhlen8","Suhlen9","SuhlenVG","SuhlenFG"]
for file in list_files:
    suhlen = pd.read_csv(f"../Join/Suhlen/{file}.csv")
    suhlen["Date/Time"] = pd.to_datetime(suhlen["Date/Time"], infer_datetime_format=True).dt.floor('H')
    suhlen = suhlen.drop(columns=["Unit"])

    a = pd.DataFrame(columns=["Date/Time"], data=pd.date_range(start=str(suhlen["Date/Time"][0]), end=suhlen["Date/Time"].iloc[-1] + pd.Timedelta(hours=1),freq='10T'))
    result = pd.merge(a,suhlen, on='Date/Time', how="outer")
    result.fillna(method='ffill', inplace=True)
    result.columns = ["Date", file]

    merged = pd.merge(merged,result, on='Date', how="outer")
    merged.sort_values(by='Date', inplace=True)

In [84]:
merged.to_csv("../environment.csv")

- Suhlen 1: Fischteiche        FTs
- Suhlen 2: Kornbrunnebnteich  KTf
- Suhlen 3: Schützen/Antoni    SAs
- Suhlen 4: Baumgartlereck     BEs
- Suhlen 5: Panzergraben neu   PGfs
- Suhlen 6: Spitz/Haupt        SHs
- Suhlen 7: Pappelwiese        PWs
- Suhlen 8: Pappelkultur       PKs
- Suhlen 9: Kastanienplantage  KPf

### Wild boards

In [3]:
path_id = "../Join/Smartbowmarken IDs_clean.xlsx"
ids = pd.read_excel(path_id)

In [4]:
ids

MACadresse Farbmarke Gatter/Fuetterung          ID
0        144461      gr02                FG  FG.2016.05
1        148376      vl06                VG  DE.2011.23
2        135316      or10                VG  IS.2011.10
3        147529      bl64                VG  FG.2013.32
4        136156      rs10                VG  IS.2011.27
..          ...       ...               ...         ...
177      133645      vl06                VG  DE.2011.23
178      137212      rs06                VG  IS.2011.23
179      153269      ge19                VG  IS.2011.37
180      140143      or13                VG  IS.2011.13
181      140838      bl36                FG  FG.2013.16

[182 rows x 4 columns]

In [5]:
print(f'Number of ids {len(ids["ID"].unique())}')
print(f'Number of MACadresse {len(ids["MACadresse"].unique())}')
print(f'Number of Farbmarke {len(ids["Farbmarke"].unique())}')

Number of ids 99
Number of MACadresse 181
Number of Farbmarke 99


In [6]:
fiwi_wild_boards = set(ids[(ids["Gatter/Fuetterung"] == "FG") | (ids["Gatter/Fuetterung"] == "VG")]["ID"])
other_wild_boards = set(ids[(ids["Gatter/Fuetterung"] != "FG") & (ids["Gatter/Fuetterung"] != "VG")]["ID"])

In [23]:
path_rm = "../Join/OverviewLogger_clean.xlsx"
rm = pd.read_excel(path_rm)
rm

ID   tag Enclosure  sc  ip.fixed     if  hr
0   DE.2011.20  vl03        VG   1     101.0    NaN NaN
1   IS.2011.13  or13        VG   2     102.0    NaN NaN
2   DE.2011.23  vl06        VG   3     103.0    NaN NaN
3   DE.2011.27  vl11        VG   4     104.0    NaN NaN
4   IS.2011.24  we01        VG   5     105.0    NaN NaN
..         ...   ...       ...  ..       ...    ...  ..
60  JG.2012.08  sz08        SE  83     164.0  184.0 NaN
61  JG.2011.07  gr09        BG  65     165.0  185.0 NaN
62  JG.2015.02  gr10        BG  67     167.0  187.0 NaN
63  JG.2015.03  gr11        BG  68     168.0  186.0 NaN
64  JG.2012.09  sz16        KP  70     170.0  145.0 NaN

[65 rows x 7 columns]

El fichero de logger, se encuentran wild boars tanto de fiwi como de la otra area, se ha decidido, dividir en dos ficheros 
ya que no tiene sentido tener a los dos juntos.

Comparar lenght del join con los ficheros separados (para darnos cuenta de que tiene distinta lenght)

In [12]:
path_sb_log = "../Join/Temperaturlogger/Loggers and Climate_separate dataframes_Subcut.csv"
path_sb_ = "../Wildschwein_Eisenstadt/Temperaturlogger/"
path_join = "../Wildschwein_Eisenstadt/Wichtige Projektfiles/binary data/Loggers and Climate_one dataframe_linear approx/Loggers and Climate_one dataframe_linear approx_AllData.approx.csv"

In [13]:
df_log = pd.read_csv(path_sb_log)
df_join = pd.read_csv(path_join)

/tmp/ipykernel_1009/128483037.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df_log = pd.read_csv(path_sb_log)


In [ ]:
list_file = [file for file in os.listdir(path_sb_) if ".csv" in file]
total = 0
for file in list_file:
    kind = "temp." + file[:2] + ".ap" #"temp.if.ap"
    wild = file[8:-4] #"JG.2015.02"
    # file = "if_2017_JG.2015.02.csv"
    df_sb = pd.read_csv(os.path.join(path_sb_,file))
    # print(file[:2],",",wild,",",len(df_sb["Date"]),",",df_sb["Date"].min(),",",df_sb["Date"].max())
    df_join_temp = df_join[df_join["ID"] == wild]
    df_join_temp = df_join_temp[df_join_temp[kind].notnull()]
    len_join = len(df_join_temp)
    # print(file[:2],",",wild,",",len_join,",",df_join_temp["Date"].min(),",",df_join_temp["Date"].max())
    print(file[:2],wild,len(df_sb["Date"]),len_join)

Actualizar columna de implanted para coger todos los datos de los ficheros de ../Wildschwein_Eisenstadt/Temperaturlogger

In [3]:
df = pd.read_csv("../Join/OverviewLogger_original.csv",encoding= 'unicode_escape')

In [6]:
list_file = [file for file in os.listdir("../Wildschwein_Eisenstadt/Temperaturlogger") if ".csv" in file]
for row in range(len(df)-1):
    element = df.iloc[row,:]["ID"]
    file = [i for i in list_file if element in i]
    if len(file)>0:
        file = file[0]
        df_pro = pd.read_csv("../Wildschwein_Eisenstadt/Temperaturlogger/" + file)
        fecha = df_pro["Date"].min()[:10]
        # print(element,df.iloc[row,:]["implanted"],fecha)
        datetime_2017 = datetime.strptime("2017-01-01", '%Y-%m-%d')
        datetime_files = datetime.strptime(fecha, '%Y-%m-%d')
        datetime_original = datetime.strptime(df.iloc[row,:]["implanted"], '%Y-%m-%d')
        if datetime_original < datetime_2017:
            df.at[row, 'implanted'] = "2017-01-01"
            pass
        if datetime_original > datetime_files:
            df.at[row, 'implanted'] = fecha
df = df.set_index("ID")
df.to_csv("../Join/OverviewLogger_join.csv")

#### Join logger with Location

##### Split linear and closest in daily files

In [40]:
path_join_linear = "../Join/Loggers and Climate_one dataframe_linear approx/Loggers and Climate_one dataframe_linear approx_AllData.approx.csv"
df_join_linear = pd.read_csv(path_join_linear)
path_join_close = "../Join/Loggers and Climate_one dataframe_closest time/Loggers and Climate_one dataframe_closest time_AllData.csv"
df_join_close = pd.read_csv(path_join_close)

/tmp/ipykernel_1009/2298428446.py:4: DtypeWarning: Columns (3,5,7,9,13,19) have mixed types. Specify dtype option on import or set low_memory=False.
  df_join_close = pd.read_csv(path_join_close)


In [41]:
min_date = df_join_linear["Date"].min()[:10]
max_date = df_join_linear["Date"].max()[:10]
list_date = pd.date_range(start=min_date,end=max_date).to_list()
df_join_linear["Date"] = pd.to_datetime(df_join_linear["Date"], infer_datetime_format=True)

In [42]:
for date in list_date:
    df_small = df_join_linear[(df_join_linear["Date"] > date) & (df_join_linear["Date"] < date + timedelta(days=1) - timedelta(seconds=1))]
    df_small.to_csv(os.path.join("../Join/logger_linear_per_day",date.strftime("%Y-%m-%d") + ".csv"))

In [46]:
min_date = df_join_close["MergeTime"].min()[:10]
max_date = df_join_close["MergeTime"].max()[:10]
list_date = pd.date_range(start=min_date,end=max_date).to_list()
df_join_close["MergeTime"] = pd.to_datetime(df_join_close["MergeTime"], infer_datetime_format=True)

In [47]:
for date in list_date:
    df_small = df_join_close[(df_join_close["MergeTime"] > date) & (df_join_close["MergeTime"] < date + timedelta(days=1) - timedelta(seconds=1))]
    df_small.to_csv(os.path.join("../Join/logger_closest_per_day",date.strftime("%Y-%m-%d") + ".csv"))

##### Clean all the position files and copy to Join folder

In [205]:
list_files_closest = os.listdir("../Join/logger_linear_per_day")

min_date = datetime.strptime(list_files_closest[0][:-4],"%Y-%m-%d")
max_date = datetime.strptime(list_files_closest[0-1][:-4],"%Y-%m-%d")

def stringtodate(name):
    str_date = name[:4] + "-" + name[4:6] + "-" + name[6:8] + " " + name[8:10] + ":" + name[10:12] + ":" + name[12:14]
    str_date = datetime.strptime(str_date,"%Y-%m-%d %H:%M:%S")
    if str_date.second >= 50 and not (str_date.minute == 59 and str_date.hour == 23):
        str_date = str_date + timedelta(minutes=1)
        str_date = str_date.replace(second=0)
    else:
        str_date = str_date.replace(second=0)
    return str_date

def is_in_range(name,min_date,max_date):
    date = name[:4] + "-" + name[4:6] + "-" + name[6:8] + " " + name[9:11] + ":" + name[11:13] + ":" + name[13:15]
    date = datetime.strptime(date,"%Y-%m-%d %H:%M:%S")
    return (date > min_date) and (date < max_date)

list_files_position = os.listdir("../Wildschwein_Eisenstadt/Telemetriedaten/positions")
# list_files_position = [file for file in list_files_position if is_in_range(file,min_date,max_date)]

for file in list_files_position:
    df = pd.read_csv(os.path.join("../Wildschwein_Eisenstadt/Telemetriedaten/positions",file),sep=";")
    df.columns = ['timestampms', 'animalname', 'tagid', 'MACadresse', 'modulversion', 'softwareversion', 'x-value', 'y-value', 'Unnamed: 8']
    df['timestampms'] = df['timestampms'].astype(str)
    df['timestampms'] = df['timestampms'].apply(stringtodate)
    result = pd.merge(df, ids, how="left", on="MACadresse")
    result = result.drop(columns=['animalname', 'modulversion',
        'softwareversion', 'Unnamed: 8', 'Farbmarke',
        'Gatter/Fuetterung'])
    result.to_csv("../Join/telemetriedaten/positions/" + file[:4] + "-" + file[4:6] + "-" + file[6:8] + ".csv")


##### Join Logger with positions v.1

In [234]:
path_save_linear = "../Join/Logger_positions_linear"
path_save_closest = "../Join/Logger_positions_closest"
path_logger_linear = "../Join/logger_linear_per_day"
path_logger_closest = "../Join/logger_closest_per_day"
path_positions = "../Join/telemetriedaten/positions"
files_positions = os.listdir(path_positions)

closest

In [237]:
files_closest =  os.listdir(path_logger_closest)

min_date = datetime.strptime(files_closest[0][:-4],"%Y-%m-%d")
max_date = datetime.strptime(files_closest[0-1][:-4],"%Y-%m-%d")
print(min_date,max_date)

2016-10-08 00:00:00 2018-12-03 00:00:00


In [247]:
# There are time in the logger that are not merge because dont have a close one.

for file in files_closest:
   df = pd.read_csv(os.path.join(path_logger_closest,file))
   df = df.drop(columns=['Unnamed: 0.1', 'Unnamed: 0', 'Date.WS', 'TempMain', 'HumMain', 'Wind',
       'WindDir', 'Rain', 'Solar', 'TempBB', 'TempForest', 'HumForest',
       'BaroPressure'])
   try:
      df_position = pd.read_csv(os.path.join(path_positions,file))
      df_position.columns = ['Unnamed: 0', 'MergeTime', 'tagid', 'MACadresse', 'x-value',
       'y-value', 'ID']
      result = pd.merge(df, df_position, how="left", on=["MergeTime","ID"])
      result = result.drop(columns=['Unnamed: 0'])
      result.to_csv(os.path.join(path_save_closest,file))
   except:
      df.to_csv(os.path.join(path_save_closest,file))

Linear

In [235]:
files_linear =  os.listdir(path_logger_linear)

min_date = datetime.strptime(files_linear[0][:-4],"%Y-%m-%d")
max_date = datetime.strptime(files_linear[0-1][:-4],"%Y-%m-%d")
print(min_date,max_date)

2016-10-08 00:00:00 2019-02-13 00:00:00


In [236]:
# There are time in the logger that are not merge because dont have a close one.

for file in files_linear:
   df = pd.read_csv(os.path.join(path_logger_linear,file))
   df = df.drop(columns=['Unnamed: 0.1', 'Unnamed: 0', 'QI', 'TempMain.ap', 'HumMain.ap',
       'TempBB.ap', 'TempForest', 'HumForest.ap', 'BaroPressure.ap'])
   try:
      df_position = pd.read_csv(os.path.join(path_positions,file))
      df_position.columns = ['Unnamed: 0', 'Date', 'tagid', 'MACadresse', 'x-value',
       'y-value', 'ID']
      result = pd.merge(df, df_position, how="left", on=["Date","ID"])
      result = result.drop(columns=['Unnamed: 0'])
      result.to_csv(os.path.join(path_save_linear,file))
   except:
      df.to_csv(os.path.join(path_save_linear,file))

El problema de esta aproximacion es que no se puede realizar realizar una aproximacion entre los datos ya que hay muchos ids,
en la siguiente version se ha pensado unificar por ids

##### Join Logger with positions v.2

In [39]:
path_save_linear = "../Join/Logger_positions_linear_v2"
path_save_closest = "../Join/Logger_positions_closest_v2"
path_logger_linear = "../Join/logger_linear_per_day"
path_logger_closest = "../Join/logger_closest_per_day"
path_positions = "../Join/telemetriedaten/positions"
files_positions = os.listdir(path_positions)

Closest

In [40]:
files_closest =  os.listdir(path_logger_closest)

min_date = datetime.strptime(files_closest[0][:-4],"%Y-%m-%d")
max_date = datetime.strptime(files_closest[0-1][:-4],"%Y-%m-%d")
print(min_date,max_date)

2016-10-08 00:00:00 2018-12-03 00:00:00


In [41]:
for file in files_closest:
    df = pd.read_csv(os.path.join(path_logger_closest,file))
    df = df.drop(columns=['Unnamed: 0.1', 'Unnamed: 0', 'Date.WS', 'TempMain', 'HumMain', 'Wind',
       'WindDir', 'Rain', 'Solar', 'TempBB', 'TempForest', 'HumForest',
       'BaroPressure'])
    df["MergeTime"] = pd.to_datetime(df["MergeTime"], infer_datetime_format=True)    

    try:
        df_position = pd.read_csv(os.path.join(path_positions,file))
        df_position.columns = ['Unnamed: 0', 'MergeTime', 'tagid', 'MACadresse', 'x-value',
        'y-value', 'ID']
        df_position["MergeTime"] = pd.to_datetime(df_position["MergeTime"], infer_datetime_format=True)    

      
        # list_wild_df = df["ID"].unique()
        # list_wild_df_position = df_position["ID"].unique()
        # join = pd.DataFrame()
        # for wild in  list_wild_df:
        #     print(wild)
        #     try:
        #         pivot = df[df["ID"]==wild]
        #         pivot_position = df_position[df_position["ID"]==wild]
        #         pivot.sort_values(by='MergeTime', inplace=True)
        #         pivot_position.sort_values(by='MergeTime', inplace=True)
        #         result = pd.merge_asof(pivot,pivot_position,on="MergeTime", by = "ID")
        #     except Exception as e:
        #         print(e)
        #         result = df[df["ID"]==wild]
        #     join = pd.concat([join,result.iloc[:,1:]])
            
        df.sort_values(by='MergeTime', inplace=True)
        df_position.sort_values(by='MergeTime', inplace=True)
        result = pd.merge_asof(df,df_position,on="MergeTime", by = "ID")
        result.to_csv(os.path.join(path_save_closest,file))
    except Exception as e:
        # print(e)
        df.to_csv(os.path.join(path_save_closest,file))


Linear

In [42]:
files_linear =  os.listdir(path_logger_linear)

min_date = datetime.strptime(files_linear[0][:-4],"%Y-%m-%d")
max_date = datetime.strptime(files_linear[0-1][:-4],"%Y-%m-%d")
print(min_date,max_date)

2016-10-08 00:00:00 2019-02-13 00:00:00


In [43]:
for file in files_linear:
   df = pd.read_csv(os.path.join(path_logger_linear,file))
   df = df.drop(columns=['Unnamed: 0.1', 'Unnamed: 0', 'QI', 'TempMain.ap', 'HumMain.ap',
       'TempBB.ap', 'TempForest', 'HumForest.ap', 'BaroPressure.ap'])
   df["Date"] = pd.to_datetime(df["Date"], infer_datetime_format=True)    

   try:
      df_position = pd.read_csv(os.path.join(path_positions,file))
      df_position.columns = ['Unnamed: 0', 'Date', 'tagid', 'MACadresse', 'x-value',
       'y-value', 'ID']
      df_position["Date"] = pd.to_datetime(df_position["Date"], infer_datetime_format=True)    

      
      df.sort_values(by='Date', inplace=True)
      df_position.sort_values(by='Date', inplace=True)
      result = pd.merge_asof(df,df_position,on="Date", by = "ID")
      result.to_csv(os.path.join(path_save_linear,file))
   except:
      df.to_csv(os.path.join(path_save_linear,file))

##### Join files

In [55]:
path_save_linear = "../Join/Logger_positions_linear"
path_save_closest = "../Join/Logger_positions_closest"
path_save_linear_v2 = "../Join/Logger_positions_linear_v2"
path_save_closest_v2 = "../Join/Logger_positions_closest_v2"

In [56]:
# Linear v1
join = pd.DataFrame()
for file in os.listdir(path_save_linear):
    df = pd.read_csv(os.path.join(path_save_linear,file))
    join = pd.concat([join,df])
join.to_csv("../Join/linear_v1.csv")

In [57]:
#Closest v1
join = pd.DataFrame()
for file in os.listdir(path_save_closest):
    df = pd.read_csv(os.path.join(path_save_closest,file))
    join = pd.concat([join,df])
join.to_csv("../Join/closest_v1.csv")

In [ ]:
# Linear v2
join = pd.DataFrame()
for file in os.listdir(path_save_linear_v2):
    df = pd.read_csv(os.path.join(path_save_linear_v2,file))
    join = pd.concat([join,df])
join.to_csv("../Join/linear_v2.csv")

In [ ]:
#Closest v2
join = pd.DataFrame()
for file in os.listdir(path_save_closest_v2):
    df = pd.read_csv(os.path.join(path_save_closest_v2,file))
    join = pd.concat([join,df])
join.to_csv("../Join/closest_v2.csv")

To do:
    - Unir position con weather
    - Unir closest y linear con weather con el closest
    - Usar 

##### Add gendle to files (Ath the end we didnt use if at all the wild are femeles)

In [3]:
path_linear_v1 = "../Join/linear_v1.csv"
path_linear_v2 = "../Join/linear_v2.csv"
path_closest_v1 = "../Join/closest_v1.csv"
path_closest_v2 = "../Join/closest_v2.csv"

In [4]:
df_gendle = pd.read_excel("../Join/MasterfileTiere.xlsx")[["ID","sex"]].iloc[:-2]

In [6]:
df = pd.read_csv(path_linear_v1)
result = pd.merge(df, df_gendle, how="left", on="ID")
result.to_csv("../Join/linear_v1_g.csv")

In [7]:
df = pd.read_csv(path_linear_v2)
result = pd.merge(df, df_gendle, how="left", on="ID")
result.to_csv("../Join/linear_v2_g.csv")

In [8]:
df = pd.read_csv(path_closest_v1)
result = pd.merge(df, df_gendle, how="left", on="ID")
result.to_csv("../Join/closest_v1_g.csv")

/tmp/ipykernel_12693/4023450071.py:1: DtypeWarning: Columns (8,10,14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path_closest_v1)


In [9]:
df = pd.read_csv(path_closest_v2)
result = pd.merge(df, df_gendle, how="left", on="ID")
result.to_csv("../Join/closest_v2_g.csv")

/tmp/ipykernel_12693/417058369.py:1: DtypeWarning: Columns (8,10,14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path_closest_v2)


##### Join logger files with weather

In [6]:
path_linear_v1 = "../Join/linear_v1.csv"
path_linear_v2 = "../Join/linear_v2.csv"
path_closest_v1 = "../Join/closest_v1.csv"
path_closest_v2 = "../Join/closest_v2.csv"
path_env = "../Join/environment.csv"

In [7]:
df_env = pd.read_csv(path_env)
df_env = df_env.drop(columns=["Unnamed: 0.1","Unnamed: 0"])
df_env["Date"] = pd.to_datetime(df_env["Date"], infer_datetime_format=True)   
df_env.sort_values(by='Date', inplace=True)

In [8]:
# Join linear v1
df = pd.read_csv(path_linear_v1)
df = df.drop(columns=["Unnamed: 0.1","Unnamed: 0"])

In [ ]:
df["Date"] = pd.to_datetime(df["Date"], infer_datetime_format=True)    
result = pd.merge_asof(df,df_env,on="Date")

In [ ]:
result.to_csv("../Join/final_linear_v1.csv")

In [ ]:
# Join linear v2
df = pd.read_csv(path_linear_v2)
df = df.drop(columns=["Unnamed: 0.1","Unnamed: 0"])

In [ ]:
df["Date"] = pd.to_datetime(df["Date"], infer_datetime_format=True)    
result = pd.merge_asof(df,df_env,on="Date")

In [ ]:
result.to_csv("../Join/final_linear_v2.csv")

In [ ]:
# Join closest v1
df = pd.read_csv(path_closest_v1)
df = df.drop(columns=["Unnamed: 0.1","Unnamed: 0"])
df.columns = ['Date', 'ID', 'Date.sc', 'temp.sc', 'Date.ip', 'temp.ip',
       'Date.if', 'temp.if', 'Date.hr', 'temp.hr', 'hr', 'hr.QI', 'Date.et',
       'temp.et', 'tagid', 'MACadresse', 'x-value', 'y-value']

/tmp/ipykernel_12649/3388026858.py:2: DtypeWarning: Columns (8,10,14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path_closest_v1)


In [ ]:
df["Date"] = pd.to_datetime(df["Date"], infer_datetime_format=True)
df.sort_values(by='Date', inplace=True) 
result = pd.merge_asof(df,df_env,on="Date")

In [ ]:
result.to_csv("../Join/final_closest_v1.csv")

In [ ]:
# Join closest v2
df = pd.read_csv(path_closest_v2)
df = df.drop(columns=["Unnamed: 0.1","Unnamed: 0",'Unnamed: 0.2'])
df.columns = ['Date', 'ID', 'Date.sc', 'temp.sc', 'Date.ip',
       'temp.ip', 'Date.if', 'temp.if', 'Date.hr', 'temp.hr', 'hr', 'hr.QI',
       'Date.et', 'temp.et', 'tagid', 'MACadresse', 'x-value', 'y-value']

/tmp/ipykernel_12649/2833326958.py:2: DtypeWarning: Columns (8,10,14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path_closest_v2)


In [ ]:
df["Date"] = pd.to_datetime(df["Date"], infer_datetime_format=True)
df.sort_values(by='Date', inplace=True) 
result = pd.merge_asof(df,df_env,on="Date")

In [ ]:
result.to_csv("../Join/final_closest_v2.csv")

##### Join position with weather

In [ ]:
df_env = pd.read_csv(path_env)
df_env = df_env.drop(columns=["Unnamed: 0.1","Unnamed: 0"])
df_env["Date"] = pd.to_datetime(df_env["Date"], infer_datetime_format=True)   
df_env.sort_values(by='Date', inplace=True)

In [71]:
path_positions = "../Join/telemetriedaten/positions"
file_positions = os.listdir(path_positions)
for file in file_positions:
    df = pd.read_csv(os.path.join(path_positions,file))
    df = df.drop(columns=["Unnamed: 0"])
    df.columns = ["Date", 'tagid', 'MACadresse', 'x-value',
       'y-value', 'ID']
    df["Date"] = pd.to_datetime(df["Date"], infer_datetime_format=True)   
    result = pd.merge_asof(df,df_env,on="Date")
    result.to_csv(f"../Join/telemetriedaten/positions_weather/{file}")

##### Split Fiwi and 

In [10]:
df = pd.read_csv("../Final_files/final_linear_v1.csv")
# for wild in df["ID"].unique():
#     print(wild,wild in fiwi_wild_boards, wild in other_wild_boards)

/tmp/ipykernel_12813/3171071423.py:1: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../Final_files/final_linear_v1.csv")


In [24]:
df_fiwi = df[df["ID"].isin(fiwi_wild_boards)]

In [25]:
df_other = df[df["ID"].isin(other_wild_boards)]

In [26]:
df_fiwi.to_csv("../Final_files/fiwi_final_linear_v1.csv")
df_other.to_csv("../Final_files/other_final_linear_v1.csv")

In [10]:
df = pd.read_csv("../Final_files/final_linear_v2.csv")
df_fiwi = df[df["ID"].isin(fiwi_wild_boards)]
df_other = df[df["ID"].isin(other_wild_boards)]
df_fiwi.to_csv("../Final_files/fiwi_final_linear_v2.csv")
df_other.to_csv("../Final_files/other_final_linear_v2.csv")

/tmp/ipykernel_208/69600001.py:1: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../Final_files/final_linear_v2.csv")


In [11]:
df = pd.read_csv("../Final_files/final_closest_v1.csv")
df_fiwi = df[df["ID"].isin(fiwi_wild_boards)]
df_other = df[df["ID"].isin(other_wild_boards)]
df_fiwi.to_csv("../Final_files/fiwi_final_closest_v1.csv")
df_other.to_csv("../Final_files/other_final_closest_v1.csv")

/tmp/ipykernel_208/2832105315.py:1: DtypeWarning: Columns (7,9,13,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../Final_files/final_closest_v1.csv")


In [12]:
df = pd.read_csv("../Final_files/final_closest_v2.csv")
df_fiwi = df[df["ID"].isin(fiwi_wild_boards)]
df_other = df[df["ID"].isin(other_wild_boards)]
df_fiwi.to_csv("../Final_files/fiwi_final_closest_v2.csv")
df_other.to_csv("../Final_files/other_final_closest_v2.csv")

/tmp/ipykernel_208/2319316170.py:1: DtypeWarning: Columns (7,9,13,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../Final_files/final_closest_v2.csv")
